---
abstract: 'simple HTTP router'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF GMAIL COM>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Router-Simple
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor::Fast: 0
  List::Util: 0
  Test::More: 0.88
  parent: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
