---
abstract: 'simple HTTP router'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Router-Simple
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Router::Simple:
    file: lib/Router/Simple.pm
    version: 0.11
  Router::Simple::Declare:
    file: lib/Router/Simple/Declare.pm
    version: 0
  Router::Simple::Route:
    file: lib/Router/Simple/Route.pm
    version: 0
  Router::Simple::SubMapper:
    file: lib/Router/Simple/SubMapper.pm
    version: 0
requires:
  Class::Accessor::Fast: 0
  List::Util: 0
  Test::More: 0.88
  parent: 0
  perl: 5.00800
resources:
  license: http://dev.perl.org/licenses/
version: 0.11
